from secrets import token_urlsafe

from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel

from core.fields import UniqueIDTextField
from users.constants import AccessTokenManagedBy


class AccessTokenManager(models.Manager):
    def get_default_token_value(self, user_id):
        """Return the value of the user's default active user-managed token, or None."""
        return (
            self.filter(
                user_id=user_id,
                managed_by=AccessTokenManagedBy.USER,
                is_default=True,
                is_active=True,
            )
            .values_list("value", flat=True)
            .first()
        )

    def get_default_token(self, user_id):
        """Return the user's default active user-managed token instance, or None."""
        return self.filter(
            user_id=user_id,
            managed_by=AccessTokenManagedBy.USER,
            is_default=True,
            is_active=True,
        ).first()

    def regenerate_default_token(self, user):
        """
        Regenerate the user's default access token.

        Replaces the current active, user-managed, default token value if it
        exists. Creates a new default token if one doesn't exist yet (improbable
        after migration, but handled gracefully as a defensive measure).

        Returns the AccessToken instance.
        """
        token_obj = self.get_default_token(user.id)
        if token_obj:
            token_obj.value = token_urlsafe()
            token_obj.save(update_fields=["value", "modified"])
        else:
            token_obj = self.create(
                user=user,
                managed_by=AccessTokenManagedBy.USER,
                is_default=True,
                is_active=True,
                label="Default",
            )
        return token_obj

    def get_user_tokens(self, user_id):
        """Return all user-managed tokens for the given user, ordered by creation date."""
        return self.filter(
            user_id=user_id,
            managed_by=AccessTokenManagedBy.USER,
        ).order_by("-created")


class AccessToken(TimeStampedModel):
    """
    A bearer token for API authentication.

    System-managed tokens are created automatically during device login
    and are tied to a Device lifecycle. User-managed tokens are created
    explicitly via the "Manage API Tokens" endpoints or the user_post_save
    signal (which creates a default token for every new user).

    Exactly one active, user-managed token per user is marked as the default
    (is_default=True). This is the token returned by GET /me/token/ and
    regenerated by POST /me/token/regenerate/. System-managed tokens cannot
    be marked as default.
    """

    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="access_tokens",
    )
    external_id = UniqueIDTextField()
    value = models.TextField(unique=True, default=token_urlsafe)
    label = models.TextField(blank=True, default="")
    managed_by = models.TextField(
        choices=AccessTokenManagedBy.choices,
        default=AccessTokenManagedBy.USER,
    )
    is_active = models.BooleanField(default=True, db_index=True)
    is_default = models.BooleanField(default=False)

    objects = AccessTokenManager()

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=~models.Q(managed_by="system", is_default=True),
                name="system_tokens_cannot_be_default",
            ),
            models.UniqueConstraint(
                fields=["user"],
                condition=models.Q(is_default=True, is_active=True, managed_by="user"),
                name="uq_user_default_active_tok",
            ),
        ]

    def __str__(self):
        return f"Token ({self.managed_by}) for {self.user}"
