# Generated by Django 5.2.3 on 2025-12-17 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["project", "-updated"],
                name="page_project_updated_idx",
            ),
        ),
    ]
