# Generated by Django 5.2.3 on 2025-12-17 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_page_project_updated_idx"),
        ("users", "0013_default_personal_email_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                condition=models.Q(("is_deleted", False)), fields=["org", "-modified"], name="project_org_mod_idx"
            ),
        ),
    ]
