# Generated by Django 5.2.3 on 2025-12-26 05:34

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_add_project_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("link_text", models.TextField()),
                (
                    "source_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_links", to="pages.page"
                    ),
                ),
                (
                    "target_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="incoming_links", to="pages.page"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source_page"], name="pagelink_source_idx"),
                    models.Index(fields=["target_page"], name="pagelink_target_idx"),
                ],
                "unique_together": {("source_page", "target_page", "link_text")},
            },
        ),
    ]
