# Generated by Django 5.2.3 on 2025-12-31 02:00

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0001_initial"),
        ("pages", "0007_add_pagelink_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="User who added this file to the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filehub.fileupload",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.project"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="files",
            field=models.ManyToManyField(
                related_name="projects",
                through="pages.ProjectFile",
                to="filehub.fileupload",
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(fields=["project", "created"], name="pages_proje_project_9dd633_idx"),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(fields=["file_upload"], name="pages_proje_file_up_a2c5cf_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectfile",
            constraint=models.UniqueConstraint(fields=("project", "file_upload"), name="project_file_uniq"),
        ),
    ]
