# Generated by Django 5.2.3 on 2026-01-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_add_pagelink_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="access_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Token for read-only public access",
                max_length=43,
                null=True,
                unique=True,
            ),
        ),
    ]
