# Generated by Django 5.2.3 on 2026-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_add_page_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="org_members_can_access",
            field=models.BooleanField(
                default=True,
                help_text="If True, all org members can access. If False, only project editors.",
            ),
        ),
    ]
