# Generated by Django 5.2.3 on 2026-01-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_add_page_access_code"),
        ("pages", "0009_remove_project_files_delete_projectfile"),
    ]

    operations = []
