# Generated by Django 5.2.3 on 2026-01-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_merge_20260106_0229"),
        ("pages", "0012_add_page_mention"),
    ]

    operations = []
