# Generated by Django 5.2.3 on 2026-03-02 01:17

import core.fields
import core.helpers.text
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_add_page_title_trgm_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="current_version_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PageVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    core.fields.UniqueIDTextField(
                        default=core.helpers.text.generate_external_id,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(max_length=64)),
                ("title", models.TextField(blank=True, default="")),
                ("content_size_bytes", models.PositiveIntegerField(default=0)),
                ("version_number", models.PositiveIntegerField()),
                ("editors", models.JSONField(default=list)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("is_compacted", models.BooleanField(default=False)),
                ("compacted_from_count", models.PositiveIntegerField(default=0)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "indexes": [
                    models.Index(
                        fields=["page", "-version_number"],
                        name="pageversion_page_vnum_idx",
                    ),
                    models.Index(fields=["page", "-created"], name="pageversion_page_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "version_number"),
                        name="unique_page_version_number",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageVersionEditorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_sessions",
                        to="pages.page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["page", "-connected_at"],
                        name="editorsession_page_conn_idx",
                    )
                ],
            },
        ),
    ]
