# Generated by Django 5.2.3 on 2026-03-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_rename_versions_to_rewind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rewind",
            options={},
        ),
    ]
