# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_alter_rewind_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewind",
            name="lines_added",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rewind",
            name="lines_deleted",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
