# Generated by Django 5.2.3 on 2026-03-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_rewind_line_diff_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewind",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
