# Generated by Django 5.2.3 on 2026-03-12 15:45

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_folder"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="folder",
            new_name="pages_folde_project_7d2d12_idx",
            old_name="pages_folde_project_b1e7b5_idx",
        ),
        migrations.AlterField(
            model_name="folder",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="folder",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
