# Generated by Django 5.2.3 on 2026-03-18 21:12

import core.fields
import core.helpers.text
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0021_rename_pages_folde_project_b1e7b5_idx_pages_folde_project_7d2d12_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    core.fields.UniqueIDTextField(
                        default=core.helpers.text.generate_external_id,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("anchor_from", models.BinaryField(blank=True, null=True)),
                ("anchor_to", models.BinaryField(blank=True, null=True)),
                ("anchor_text", models.TextField(blank=True, default="")),
                ("body", models.TextField()),
                (
                    "ai_persona",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("socrates", "Socrates"),
                            ("einstein", "Einstein"),
                            ("dewey", "Dewey"),
                        ],
                        default="",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pages.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="pages.comment",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["page", "created"], name="comment_page_created_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("parent__isnull", True),
                            models.Q(
                                ("anchor_from__isnull", True),
                                ("anchor_to__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="replies_no_anchor",
                    )
                ],
            },
        ),
    ]
