# Generated by Django 5.2.3 on 2026-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ai_persona",
            field=models.TextField(
                blank=True,
                choices=[
                    ("socrates", "Socrates"),
                    ("einstein", "Einstein"),
                    ("dewey", "Dewey"),
                    ("athena", "Athena"),
                ],
                default="",
            ),
        ),
    ]
