# Generated by Django 5.2.3 on 2026-03-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0023_add_athena_persona"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_descendants",
                to="pages.comment",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["root", "created"], name="comment_root_created_idx"),
        ),
    ]
