# Generated by Django 5.2.3 on 2026-03-25 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_backfill_comment_root"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="depth",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(condition=models.Q(("depth__lt", 8)), name="comment_max_depth"),
        ),
    ]
