# Generated by Django 5.2.3 on 2026-04-17 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0029_commentreaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="replies_no_anchor",
        ),
        migrations.AddField(
            model_name="comment",
            name="pdf_anchor",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", True),
                    models.Q(
                        ("anchor_from__isnull", True),
                        ("anchor_to__isnull", True),
                        ("pdf_anchor__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="replies_no_anchor",
            ),
        ),
    ]
