# Generated by Django 5.2.3 on 2025-12-14 08:21

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ask", "0001_initial"),
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AskRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("external_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("query", models.TextField()),
                ("asked", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("answer", models.TextField(blank=True, default=None, null=True)),
                ("results", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("replied", models.DateTimeField(db_index=True, default=None, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[("pending", "Pending"), ("ok", "OK"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                    ),
                ),
                (
                    "provider",
                    models.TextField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic"), ("google", "Google")],
                        db_index=True,
                        default="openai",
                    ),
                ),
                ("error", models.TextField(blank=True, db_index=True, default="")),
                ("details", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ask_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageEmbedding",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding",
                        serialize=False,
                        to="pages.page",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("content_hash", models.TextField(blank=True, default="")),
                ("computed", models.DateTimeField(db_index=True)),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        fields=["embedding"], name="page_embedding_hnsw_idx", opclasses=["vector_cosine_ops"]
                    )
                ],
            },
        ),
    ]
