# Generated by Django 5.2.3 on 2026-01-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ask", "0002_askrequest"),
        ("users", "0018_add_ai_config_to_askrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="askrequest",
            name="ai_config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ask_requests",
                to="users.aiproviderconfig",
            ),
        ),
        migrations.AlterField(
            model_name="askrequest",
            name="provider",
            field=models.TextField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="openai",
            ),
        ),
    ]
