# Generated by Django 5.2.3 on 2026-05-12 18:36

import django.db.models.deletion
import django_extensions.db.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ask", "0003_add_ai_config_to_askrequest"),
        ("pages", "0030_add_comment_pdf_anchor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("model", models.TextField()),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=12),
                ),
                (
                    "kind",
                    models.TextField(choices=[("index", "Index"), ("query", "Query")], db_index=True),
                ),
                (
                    "key_source",
                    models.TextField(
                        choices=[
                            ("server", "Server"),
                            ("user", "User"),
                            ("explicit", "Explicit"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_usages",
                        to="pages.page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created"], name="ask_embeddi_created_9b0cc1_idx"),
                    models.Index(
                        fields=["user", "created"],
                        name="ask_embeddi_user_id_77b544_idx",
                    ),
                    models.Index(
                        fields=["key_source", "created"],
                        name="ask_embeddi_key_sou_cc08d1_idx",
                    ),
                ],
            },
        ),
    ]
