# Generated by Django 5.2.3 on 2026-05-14 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ask", "0004_add_embedding_usage"),
        ("pages", "0030_add_comment_pdf_anchor"),
        ("users", "0031_add_daily_note_prefs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingusage",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embedding_usages",
                to="users.org",
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingusage",
            index=models.Index(fields=["org", "created"], name="ask_embeddi_org_id_3e6ad2_idx"),
        ),
    ]
