# Generated by Django 5.2.3 on 2025-12-31 02:00

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("deleted", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending_url", "Pending URL"),
                            ("finalizing", "Finalizing"),
                            ("available", "Available"),
                            ("failed", "Failed"),
                        ],
                        default="pending_url",
                    ),
                ),
                ("filename", models.TextField()),
                ("content_type", models.TextField()),
                ("expected_size", models.BigIntegerField()),
                ("checksum_sha256", models.TextField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("deleted", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "provider",
                    models.TextField(choices=[("local", "Local Filesystem"), ("r2", "Cloudflare R2")]),
                ),
                ("bucket", models.TextField(blank=True, null=True)),
                ("object_key", models.TextField()),
                ("size_bytes", models.BigIntegerField(null=True)),
                ("etag", models.TextField(blank=True, null=True)),
                ("checksum_sha256", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                    ),
                ),
                ("verified", models.DateTimeField(blank=True, null=True)),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blobs",
                        to="filehub.fileupload",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(fields=["uploaded_by", "created"], name="filehub_fil_uploade_555418_idx"),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(fields=["status", "created"], name="filehub_fil_status_b88385_idx"),
        ),
        migrations.AddIndex(
            model_name="blob",
            index=models.Index(fields=["file_upload", "status"], name="filehub_blo_file_up_e18f01_idx"),
        ),
        migrations.AddConstraint(
            model_name="blob",
            constraint=models.UniqueConstraint(
                fields=("provider", "bucket", "object_key"),
                name="filehub_unique_blob_location",
            ),
        ),
    ]
