# Generated by Django 5.2.3 on 2025-12-31 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0001_initial"),
        ("pages", "0008_projectfile_project_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_uploads",
                to="pages.project",
            ),
        ),
    ]
