# Generated by Django 5.2.3 on 2026-01-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0004_remove_projectfile_and_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="access_token",
            field=models.TextField(
                blank=True,
                db_index=True,
                null=True,
                unique=True,
            ),
        ),
    ]
