# Generated by Django 5.2.3 on 2026-01-02 04:21

import secrets

from django.db import migrations


def generate_access_tokens(apps, schema_editor):
    """Generate access tokens for all existing FileUpload records."""
    FileUpload = apps.get_model("filehub", "FileUpload")

    for file_upload in FileUpload.objects.filter(access_token__isnull=True):
        # token_urlsafe(9) produces 12 base64url characters
        file_upload.access_token = secrets.token_urlsafe(9)
        file_upload.save(update_fields=["access_token"])


def reverse_migration(apps, schema_editor):
    """Clear all access tokens (reverse migration)."""
    FileUpload = apps.get_model("filehub", "FileUpload")
    FileUpload.objects.update(access_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0005_fileupload_access_token"),
    ]

    operations = [
        migrations.RunPython(generate_access_tokens, reverse_migration),
    ]
