# Generated by Django 5.2.3 on 2026-01-02 04:24

import filehub.models.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0006_backfill_access_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="access_token",
            field=models.TextField(
                db_index=True,
                default=filehub.models.uploads._generate_file_upload_access_token,
                unique=True,
            ),
        ),
    ]
