# Generated by Django 5.2.3 on 2026-01-06 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0007_make_access_token_non_nullable"),
        ("pages", "0010_merge_20260106_0229"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["project", "external_id", "access_token"],
                name="filehub_fil_project_a9488c_idx",
            ),
        ),
    ]
