# Generated by Django 5.2.3 on 2026-02-05 04:49

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0008_add_download_lookup_index"),
        ("pages", "0014_add_page_title_trgm_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("link_text", models.TextField()),
                (
                    "source_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_links",
                        to="pages.page",
                    ),
                ),
                (
                    "target_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_references",
                        to="filehub.fileupload",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source_page"], name="filelink_source_idx"),
                    models.Index(fields=["target_file"], name="filelink_target_idx"),
                ],
                "unique_together": {("source_page", "target_file", "link_text")},
            },
        ),
    ]
