# Generated by Django 5.2.3 on 2026-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0009_add_filelink_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="actual_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
