# Generated by Django 5.2.3 on 2026-04-07 05:32

from django.db import migrations, models


def backfill_actual_size(apps, schema_editor):
    """Populate actual_size on AVAILABLE FileUploads from their verified Blob."""
    FileUpload = apps.get_model("filehub", "FileUpload")
    Blob = apps.get_model("filehub", "Blob")

    FileUpload.objects.filter(status="available", actual_size__isnull=True,).update(
        actual_size=models.Subquery(
            Blob.objects.filter(file_upload=models.OuterRef("pk"), status="verified", size_bytes__isnull=False,).values(
                "size_bytes"
            )[:1]
        )
    )


def reverse_backfill(apps, schema_editor):
    """Clear actual_size (reverse migration)."""
    FileUpload = apps.get_model("filehub", "FileUpload")
    FileUpload.objects.filter(actual_size__isnull=False).update(actual_size=None)


class Migration(migrations.Migration):

    dependencies = [
        ("filehub", "0010_add_actual_size_to_fileupload"),
    ]

    operations = [
        migrations.RunPython(backfill_actual_size, reverse_backfill),
    ]
