# Generated by Django 5.2.3 on 2025-11-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YSnapshot",
            fields=[
                ("room_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("snapshot", models.BinaryField()),
                ("last_update_id", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "y_snapshots",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YUpdate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_id", models.CharField(db_index=True, max_length=255)),
                ("yupdate", models.BinaryField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "y_updates",
                "managed": False,
            },
        ),
    ]
