# Generated by Django 5.2.3 on 2025-11-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create append-only CRDT updates table
            CREATE TABLE IF NOT EXISTS y_updates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                room_id VARCHAR(255) NOT NULL,
                yupdate BYTEA NOT NULL,
                timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            -- Composite index for fast per-room replay
            CREATE INDEX IF NOT EXISTS idx_y_updates_room_id
                ON y_updates (room_id, id);

            -- Optional BRIN index for large time-based scans
            CREATE INDEX IF NOT EXISTS brin_y_updates_ts
                ON y_updates USING BRIN (timestamp);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS brin_y_updates_ts;
            DROP INDEX IF EXISTS idx_y_updates_room_id;
            DROP TABLE IF EXISTS y_updates CASCADE;
            """,
        ),
        migrations.RunSQL(
            sql="""
            -- Create CRDT snapshots table (one row per room)
            CREATE TABLE IF NOT EXISTS y_snapshots (
                room_id VARCHAR(255) PRIMARY KEY,
                snapshot BYTEA NOT NULL,
                last_update_id BIGINT NOT NULL,
                timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            -- Index for efficient lookups (redundant with PK but explicit)
            CREATE INDEX IF NOT EXISTS idx_y_snapshots_room_id
                ON y_snapshots (room_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_y_snapshots_room_id;
            DROP TABLE IF EXISTS y_snapshots CASCADE;
            """,
        ),
    ]
