# Generated by Django 5.2.3 on 2026-03-06 10:10

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0002_create_crdt_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrdtArchiveBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("room_id", models.CharField(db_index=True, max_length=255)),
                ("from_update_id", models.BigIntegerField()),
                ("to_update_id", models.BigIntegerField()),
                ("row_count", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploaded", "Uploaded"),
                            ("verified", "Verified"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("provider", models.CharField(max_length=20)),
                ("bucket", models.CharField(max_length=255)),
                ("object_key", models.CharField(max_length=512)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("archive_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "cutoff_timestamp",
                    models.DateTimeField(help_text="Cutoff used when this batch was created"),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["room_id", "status"], name="archive_room_status_idx"),
                    models.Index(fields=["status", "created"], name="archive_status_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room_id", "from_update_id", "to_update_id"),
                        name="unique_archive_batch_range",
                    )
                ],
            },
        ),
    ]
