# Generated by Django 5.2.3 on 2026-03-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0003_crdtarchivebatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crdtarchivebatch",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
