# Generated by Django 5.2.3 on 2026-01-08 02:40

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0010_merge_20260106_0229"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "provider",
                    models.TextField(choices=[("notion", "Notion")], default="notion"),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                    ),
                ),
                ("total_pages", models.IntegerField(default=0)),
                ("pages_imported_count", models.IntegerField(default=0)),
                ("pages_failed_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="pages.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ImportedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("original_path", models.TextField()),
                ("notion_hash", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_records",
                        to="pages.page",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_pages",
                        to="imports.importjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("provider", models.TextField(default="r2")),
                ("bucket", models.TextField(blank=True, null=True)),
                ("object_key", models.TextField()),
                ("filename", models.TextField()),
                ("content_type", models.TextField(default="application/zip")),
                ("size_bytes", models.BigIntegerField()),
                ("etag", models.TextField(blank=True, null=True)),
                (
                    "import_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive",
                        to="imports.importjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["user", "status"], name="imports_imp_user_id_2d6f3e_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["user", "-created"], name="imports_imp_user_id_52dc2e_idx"),
        ),
        migrations.AddIndex(
            model_name="importedpage",
            index=models.Index(fields=["import_job"], name="imports_imp_import__ab2e92_idx"),
        ),
        migrations.AddIndex(
            model_name="importedpage",
            index=models.Index(fields=["notion_hash"], name="imports_imp_notion__3c0158_idx"),
        ),
        migrations.AddConstraint(
            model_name="importedpage",
            constraint=models.UniqueConstraint(fields=("import_job", "page"), name="imports_unique_job_page"),
        ),
        migrations.AddIndex(
            model_name="importarchive",
            index=models.Index(fields=["import_job"], name="imports_imp_import__61f53a_idx"),
        ),
    ]
