# Generated by Django 5.2.3 on 2026-01-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importarchive",
            name="temp_file_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importarchive",
            name="object_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="importarchive",
            name="size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
