# Generated by Django 5.2.3 on 2026-01-09 09:00

import django.db.models.deletion
from django.db import migrations, models


def populate_project_from_import_job(apps, schema_editor):
    """Populate project field from import_job.project for existing rows."""
    ImportedPage = apps.get_model("imports", "ImportedPage")
    for imported_page in ImportedPage.objects.select_related("import_job").all():
        imported_page.project = imported_page.import_job.project
        imported_page.save(update_fields=["project"])


def reverse_populate_project(apps, schema_editor):
    """Reverse migration - nothing to do, field will be dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_add_temp_file_path_to_archive"),
        ("pages", "0001_initial"),
    ]

    operations = [
        # Step 1: Add project field as nullable
        migrations.AddField(
            model_name="importedpage",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_pages",
                to="pages.project",
            ),
        ),
        # Step 2: Populate project from import_job.project
        migrations.RunPython(
            populate_project_from_import_job,
            reverse_populate_project,
        ),
        # Step 3: Make project non-nullable
        migrations.AlterField(
            model_name="importedpage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_pages",
                to="pages.project",
            ),
        ),
        # Step 4: Add pages_skipped_count to ImportJob
        migrations.AddField(
            model_name="importjob",
            name="pages_skipped_count",
            field=models.IntegerField(default=0),
        ),
        # Step 5: Add index for (project, notion_hash)
        migrations.AddIndex(
            model_name="importedpage",
            index=models.Index(
                fields=["project", "notion_hash"],
                name="imports_imp_project_8a4e5c_idx",
            ),
        ),
        # Step 6: Add unique constraint for deduplication
        # Only applies when notion_hash is not empty
        migrations.AddConstraint(
            model_name="importedpage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("notion_hash__gt", "")),
                fields=("project", "notion_hash"),
                name="imports_unique_project_notion_hash",
            ),
        ),
    ]
