# Generated by Django 5.2.3 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Rename notion_hash to source_hash for provider-agnostic deduplication.

    This supports multiple import providers (Notion, Obsidian, etc.) where each
    provider has its own strategy for generating source identifiers:
    - Notion: hash extracted from filename (e.g., "abc123def456")
    - Obsidian: relative filepath (e.g., "Daily Notes/2024-01-15.md")
    """

    dependencies = [
        ("imports", "0003_add_deduplication_support"),
    ]

    operations = [
        # Step 1: Remove old constraint (uses notion_hash)
        migrations.RemoveConstraint(
            model_name="importedpage",
            name="imports_unique_project_notion_hash",
        ),
        # Step 2: Remove old indexes (use notion_hash)
        migrations.RemoveIndex(
            model_name="importedpage",
            name="imports_imp_project_8a4e5c_idx",
        ),
        migrations.RemoveIndex(
            model_name="importedpage",
            name="imports_imp_notion__3c0158_idx",
        ),
        # Step 3: Rename the field
        migrations.RenameField(
            model_name="importedpage",
            old_name="notion_hash",
            new_name="source_hash",
        ),
        # Step 4: Add new indexes (use source_hash)
        migrations.AddIndex(
            model_name="importedpage",
            index=models.Index(
                fields=["source_hash"],
                name="imports_imp_source__a1b2c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importedpage",
            index=models.Index(
                fields=["project", "source_hash"],
                name="imports_imp_project_d4e5f6_idx",
            ),
        ),
        # Step 5: Add new constraint (uses source_hash)
        migrations.AddConstraint(
            model_name="importedpage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_hash__gt", "")),
                fields=("project", "source_hash"),
                name="imports_unique_project_source_hash",
            ),
        ),
    ]
