# Generated by Django 5.2.3 on 2026-01-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_rename_notion_hash_to_source_hash"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importedpage",
            new_name="imports_imp_source__74394f_idx",
            old_name="imports_imp_source__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="importedpage",
            new_name="imports_imp_project_cbc6ac_idx",
            old_name="imports_imp_project_d4e5f6_idx",
        ),
    ]
