# Generated by Django 5.2.3 on 2026-01-11 05:28

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0006_add_abuse_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBannedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "enforced",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this ban is currently enforced. Uncheck to lift the ban.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_ban",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Banned User",
                "verbose_name_plural": "Import Banned Users",
                "indexes": [
                    models.Index(fields=["enforced"], name="imports_imp_enforce_9bff27_idx"),
                    models.Index(fields=["created"], name="imports_imp_created_6b853f_idx"),
                ],
            },
        ),
    ]
