# Generated by Django 5.2.3 on 2026-01-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="spam_rules",
            field=models.JSONField(blank=True, help_text="SpamAssassin rules that triggered", null=True),
        ),
        migrations.AddField(
            model_name="update",
            name="spam_score",
            field=models.FloatField(blank=True, help_text="SpamAssassin score from test email", null=True),
        ),
    ]
