# Generated by Django 5.2.3 on 2025-06-12 11:51

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("picture", models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ("tz", models.TextField(default=None, null=True)),
                ("plan", models.TextField(choices=[("free", "Free")], db_index=True, default="free")),
                ("stripe_subscription_id", models.TextField(default=None, null=True)),
                ("stripe_customer_id", models.TextField(default=None, null=True)),
                ("stripe_payment_failed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
