# Generated by Django 5.2.3 on 2025-06-12 11:57

from django.contrib.auth import get_user_model
from django.db import migrations


def set_profile_for_users(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")

    for user_id in get_user_model().objects.filter(profile__isnull=True).values_list("id", flat=True).order_by("id"):
        Profile.objects.create(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.RunPython(
            code=set_profile_for_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
