# Generated by Django 5.2.3 on 2025-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_set_user_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="plan",
            field=models.TextField(
                choices=[("free", "Free"), ("pro", "Placeholder premium plan")], db_index=True, default="free"
            ),
        ),
    ]
