# Generated by Django 5.2.3 on 2025-06-22 05:50

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_stripelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="access_token",
            field=models.TextField(default=secrets.token_urlsafe, unique=True),
        ),
    ]
