# Generated by Django 5.2.3 on 2025-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_uesr_email_uniq"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_id",
            field=models.TextField(default=None, null=True),
        ),
    ]
