# Generated by Django 5.2.3 on 2025-11-12 06:39

from django.contrib.auth import get_user_model
from django.db import migrations

from core.helpers import generate_external_id


def set_user_external_id(apps, schema_editor):
    users = []

    for u in get_user_model().objects.filter(external_id__isnull=True).all():
        if u.external_id:
            continue

        u.external_id = generate_external_id()
        users.append(u)

    if users:
        get_user_model().objects.bulk_update(users, fields=["external_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_external_id"),
    ]

    operations = [
        migrations.RunPython(
            code=set_user_external_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
