# Generated by Django 5.2.3 on 2025-11-12 06:53

import core.fields
import core.helpers.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_external_id_existing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=core.fields.UniqueIDTextField(
                default=core.helpers.text.generate_external_id, editable=False, unique=True
            ),
        ),
    ]
