# Generated by Django 5.2.3 on 2025-12-14 04:21

import core.fields
import core.helpers.text
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_external_id_uniq_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    core.fields.UniqueIDTextField(
                        default=core.helpers.text.generate_external_id, editable=False, unique=True
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("domain", models.TextField(default=None, null=True, unique=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrgMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("role", models.TextField(choices=[("admin", "Admin"), ("member", "Member")], default="member")),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.org")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="org",
            name="members",
            field=models.ManyToManyField(related_name="orgs", through="users.OrgMember", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.UniqueConstraint(fields=("org_id", "user_id"), name="org_user_uniq"),
        ),
    ]
