# Generated by Django 5.2.3 on 2025-12-17 05:22

from django.db import migrations


# Initial list of domain substrings
# Add entries in admin

DEFAULT_PERSONAL_EMAIL_DOMAIN_SUBSTRINGS = [
    "gmail",
    "yahoo",
]


def create_initial_email_domain_substrings(apps, schema_editor):
    PersonalEmailDomain = apps.get_model("users", "PersonalEmailDomain")
    entries = [PersonalEmailDomain(substring=substring) for substring in DEFAULT_PERSONAL_EMAIL_DOMAIN_SUBSTRINGS]
    PersonalEmailDomain.objects.bulk_create(entries, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_personalemaildomain"),
    ]

    operations = [
        migrations.RunPython(
            code=create_initial_email_domain_substrings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
