# Generated by Django 5.2.3 on 2026-01-02 00:44

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_ai_provider_config"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiproviderconfig",
            new_name="users_aipro_user_id_b3c716_idx",
            old_name="users_aipro_user_id_7e5a7c_idx",
        ),
        migrations.RenameIndex(
            model_name="aiproviderconfig",
            new_name="users_aipro_org_id_ce4c7d_idx",
            old_name="users_aipro_org_id_2a6e8f_idx",
        ),
        migrations.RenameIndex(
            model_name="aiproviderconfig",
            new_name="users_aipro_user_id_e134ce_idx",
            old_name="users_aipro_user_id_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="aiproviderconfig",
            new_name="users_aipro_org_id_9243d1_idx",
            old_name="users_aipro_org_id_d4e5f6_idx",
        ),
        migrations.AlterField(
            model_name="aiproviderconfig",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="aiproviderconfig",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
