# Generated by Django 5.2.3 on 2026-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_add_ai_config_to_askrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_product_updates",
            field=models.BooleanField(default=True),
        ),
    ]
