# Generated by Django 5.2.3 on 2026-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_user_last_active_user_receive_product_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_product_updates",
            field=models.BooleanField(default=True),
        ),
    ]
