# Generated by Django 5.2.3 on 2026-01-02 23:03

from django.db import migrations


def migrate_activity_to_profile(apps, schema_editor):
    User = apps.get_model("users", "User")
    Profile = apps.get_model("users", "Profile")

    for user in User.objects.all():
        Profile.objects.filter(user=user).update(
            last_active=user.last_active,
            receive_product_updates=user.receive_product_updates,
        )


def migrate_activity_to_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    Profile = apps.get_model("users", "Profile")

    for profile in Profile.objects.select_related("user").all():
        profile.user.last_active = profile.last_active
        profile.user.receive_product_updates = profile.receive_product_updates
        profile.user.save(update_fields=["last_active", "receive_product_updates"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_add_profile_activity_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_activity_to_profile, migrate_activity_to_user),
    ]
