# Generated by Django 5.2.3 on 2026-01-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_migrate_user_activity_to_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="receive_product_updates",
        ),
    ]
