# Generated by Django 5.2.3 on 2026-01-11 11:37

import django.core.validators
import django.db.models.functions.text
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0022_remove_user_activity_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        message="Username can only contain letters, numbers, dots, hyphens, and underscores.",
                        regex="^[a-zA-Z0-9._-]+$",
                    ),
                    users.validators.validate_username_not_reserved,
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="users_user_username_ci_unique",
            ),
        ),
    ]
