# Generated by Django 5.2.3 on 2026-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_username_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="demo_visits",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
