# Generated by Django 5.2.3 on 2026-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_add_demo_visits_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="keyboard_shortcuts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
