# Generated by Django 5.2.3 on 2026-03-14 09:58

import django.db.models.deletion
import django_extensions.db.fields
import secrets
from django.conf import settings
from django.db import migrations, models

import core.fields
import core.helpers.text


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_add_keyboard_shortcuts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    core.fields.UniqueIDTextField(
                        default=core.helpers.text.generate_external_id,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(default=secrets.token_urlsafe, unique=True)),
                ("label", models.TextField(blank=True, default="")),
                (
                    "managed_by",
                    models.TextField(choices=[("system", "System"), ("user", "User")], default="user"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
