# Generated by Django 5.2.3 on 2026-03-14 09:58

import core.fields
import core.helpers.text
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_add_access_token_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "external_id",
                    core.fields.UniqueIDTextField(
                        default=core.helpers.text.generate_external_id,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("client_id", models.TextField()),
                (
                    "client_type",
                    models.TextField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("browser", "Browser"),
                            ("cli", "CLI"),
                        ],
                        default="mobile",
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("os", models.TextField(blank=True, default="")),
                ("app_version", models.TextField(blank=True, default="")),
                ("push_token", models.TextField(blank=True, default="")),
                (
                    "last_active",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("details", models.JSONField(default=dict)),
                (
                    "access_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device",
                        to="users.accesstoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "client_id"), name="unique_user_client_id")],
            },
        ),
    ]
