# Generated by Django 5.2.3 on 2026-03-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_add_device_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesstoken",
            options={},
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="accesstoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_default", True), ("managed_by", "system"), _negated=True),
                name="system_tokens_cannot_be_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesstoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True), ("managed_by", "user")),
                fields=("user",),
                name="uq_user_default_active_tok",
            ),
        ),
    ]
