# Generated by Django 5.2.3 on 2026-03-17 03:59

from django.db import migrations


def forwards(apps, schema_editor):
    """Copy each Profile.access_token value into an AccessToken row."""
    Profile = apps.get_model("users", "Profile")
    AccessToken = apps.get_model("users", "AccessToken")

    batch_size = 1000
    profiles = Profile.objects.exclude(access_token__isnull=True).exclude(access_token="")

    batch = []
    for profile in profiles.iterator(chunk_size=batch_size):
        batch.append(
            AccessToken(
                user_id=profile.user_id,
                value=profile.access_token,
                label="Default",
                managed_by="user",
                is_active=True,
                is_default=True,
            )
        )
        if len(batch) >= batch_size:
            AccessToken.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        AccessToken.objects.bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_add_is_default_to_access_token"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
