# Generated by Django 5.2.3 on 2026-03-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_migrate_profile_tokens_to_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="access_token",
        ),
    ]
