# Generated by Django 5.2.3 on 2025-06-17 09:55

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("to_address", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.TextField()),
                ("text_content", models.TextField(default=None, null=True)),
                ("html_content", models.TextField(default=None, null=True)),
                ("status_code", models.TextField(default="unknown")),
                ("message_id", models.TextField(db_index=True, default=None, null=True)),
                ("batch_id", models.TextField(db_index=True, default=None, null=True)),
                ("esp_name", models.TextField(default=None, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
