# Generated by Django 5.2.3 on 2026-01-02 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("updates", "0002_email_logging_and_spam_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentemail",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="sentemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("transactional", "Transactional"),
                    ("broadcast", "Broadcast"),
                ],
                default="transactional",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="from_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="related_update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="updates.update",
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="spam_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("spam_complaint", "Spam Complaint"),
                    ("failed", "Failed"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
    ]
